sudo: false

cache:
  - pip

dist: trusty

language: python

python:
  - '3.6'
  - '2.7'

script:
  - ./.travis.sh

after_success:
  - |
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PYTHON_VERSION" = "3.6" ]; then
      ./generate_readme.py > README.md
      ./.travis_push.sh README.md .readme examples/.readme
    fi

branches:
  only:
    - master

notifications:
  email: false
